services:
  app:
    #image: learnedmachine/speakr:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: speakr
    restart: unless-stopped
    ports:
      - "8899:8899"

    env_file:
      - .env
    
    environment:
      - LOG_LEVEL=INFO

    volumes:
      - ./uploads:/data/uploads
      - ./instance:/data/instance
